nav:
  - Accueil: index.md
  - Faire évoluer sa nation: 
    - nation/index.md
    - Les ères: 
      - Age du Bois ( défaut ) : nation/era/bois.md
      - Age de Pierre: nation/era/pierre.md
  ##- Installation et Configuration:
  ##  - install/index.md 
  ##  - Configuration : install/configuration.md
  ##  - Rejoindre le serveur : install/rejoindre.md
  - Le Monde :
    - monde/index.md
    - En Bref: monde/enbref.md
  - Jouer sur Randomia: 
    - jouer/index.md
  - Guide des mods : 
    - guide/index.md




site_name: Randomia wiki
repo_url: https://github.com/Random-Palace/wiki
repo_name: Random-Palace/wiki
copyright: Copyright &copy; 2024 Random Palace
extra:
  homepage: https://randomia.random-palace.fr/
  generator: false
  social :
    - icon: simple/discord
      link: https://discord.gg/aG6d7EGst5
    - icon: fontawesome/brands/github
      link: https://github.com/Random-Palace

theme:
  favicon: assets/images/favicon.png
  logo : assets/images/favicon.png
  features:
    - navigation.footer
    - navigation.top
    - navigation.path
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.tabs
  name: material
  language: fr
  palette: 
  # Palette toggle for light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true