nav:
    - Accueil: index.md
    - Installation et Configuration:
        - install/index.md 
        - Configuration : install/configuration.md
        - Rejoindre le serveur : install/rejoindre.md



site_name: Randomia wiki
repo_url: https://github.com/Random-Palace/wiki
repo_name: Random-Palace/wiki
copyright: Copyright &copy; 2023 Random Palace
extra:
  homepage: https://randomia.random-palace.fr/
  generator: false
theme:
    features:
        - navigation.footer
        - navigation.top
        - navigation.path
        - navigation.expand
        - navigation.sections
        - navigation.instant
        - navigation.tabs
    name: material
    language: fr
    palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true